version: '3'

services:
  app:
    container_name: src
    image: src
    build:
      context: ./src
      dockerfile: "Dockerfile"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    restart: always